name: Build

on:
    workflow_dispatch:
    pull_request:
        branches:
            - main
    push:
        branches:
            - main

jobs:
    build:
        uses: NordicSemiconductor/pc-nrfconnect-shared/.github/workflows/build.yml@main
        secrets: inherit